/**
 * SARAI ERP — central bilingual dictionary.
 * EVERY user-facing string in the application lives here. No hard-coded UI
 * strings anywhere else. Rendered via <L k="..."/> (English + Pashto RTL).
 *
 * DRAFT-PS: all Pashto strings in this file are drafts — the client will
 * verify final wording before go-live.
 */

export interface Label {
  en: string;
  ps: string;
}

export const labels = {
  // ---------------------------------------------------------------- brand
  app_name: { en: "Waheed Ghani", ps: "وحید غني" },
  app_subtitle: { en: "Import & Distribution ERP", ps: "د وارداتو او وېش سیسټم" },

  // ---------------------------------------------------------------- modules
  home: { en: "Home", ps: "کور" },
  purchasing: { en: "Purchasing", ps: "پیرودنه" },
  orders: { en: "Orders", ps: "آرډرونه" },
  inventory: { en: "Inventory", ps: "ذخیره" },
  warehouses: { en: "Warehouses", ps: "سرایونه" },
  sarafs: { en: "Sarafs", ps: "صرافان" },
  roznamcha: { en: "Daily Cash Book", ps: "روزنامچه" },
  expenses: { en: "Expenses", ps: "لګښتونه" },
  reports: { en: "Reports", ps: "راپورونه" },
  administration: { en: "Administration", ps: "اداره" },

  // ---------------------------------------------------------------- submenus / screens
  purchase_invoices: { en: "Purchase Invoices", ps: "د پیرودنې بلونه" },
  suppliers: { en: "Suppliers", ps: "عرضه کوونکې کمپنۍ" },
  supplier_payments: { en: "Supplier Payments", ps: "د عرضه کوونکو تادیات" },
  order_book: { en: "Order Book", ps: "د آرډر کتاب" },
  truck_receipts: { en: "Truck Receipts", ps: "د لارۍ رسیدونه" },
  order_expenses: { en: "Route Expenses", ps: "د لارې لګښتونه" },
  landed_cost: { en: "Landed Cost", ps: "تمام شده قیمت" },
  stock_overview: { en: "Stock Overview", ps: "د ذخیرې کتنه" },
  dispatch_invoices: { en: "Dispatch Invoices", ps: "د لېږد بلونه" },
  warehouse_payments: { en: "Warehouse Payments", ps: "د سرای تادیات" },
  saraf_transactions: { en: "Saraf Transactions", ps: "د صراف راکړې ورکړې" },
  office_expenses: { en: "Office Expenses", ps: "د دفتر لګښتونه" },
  expense_categories: { en: "Expense Categories", ps: "د لګښت ډولونه" },
  users: { en: "Users", ps: "کارونکي" },
  audit_log: { en: "Audit Log", ps: "د پلټنې یادداشت" },
  data_health: { en: "Data Health", ps: "د معلوماتو روغتیا" },
  reconciliation: { en: "Reconciliation", ps: "حساب برابرول" },
  my_warehouse: { en: "My Warehouse", ps: "زما سرای" },
  buyer_pickups: { en: "Buyer Pickups", ps: "د پیرودونکو وړل" },
  money_ledger: { en: "Money Ledger", ps: "د پیسو کتاب" },
  stock_ledger: { en: "Stock Ledger", ps: "د ذخیرې کتاب" },

  // ---------------------------------------------------------------- glossary (spec Section 9)
  date: { en: "Date", ps: "نېټه" },
  description: { en: "Description", ps: "تفصیل" },
  quantity: { en: "Quantity", ps: "مقدار" },
  price: { en: "Price", ps: "بیه" },
  total: { en: "Total", ps: "ټوله" },
  amount: { en: "Amount", ps: "مبلغ" },
  balance: { en: "Balance", ps: "پاتې حساب" },
  payment: { en: "Payment", ps: "تادیه" },
  advance_payment: { en: "Advance Payment", ps: "پیشکي تادیه" },
  remaining: { en: "Remaining", ps: "پاتې" },
  invoice: { en: "Invoice", ps: "بل" },
  invoice_no: { en: "Invoice No.", ps: "د بل نمبر" },
  container_no: { en: "Container No.", ps: "د کانټینر نمبر" },
  containers: { en: "Containers", ps: "کانټینرونه" },
  bill_of_lading: { en: "Bill of Lading", ps: "بارنامه" },
  truck: { en: "Truck", ps: "لارۍ / موټر" },
  trucks: { en: "Trucks", ps: "لارۍ" },
  warehouse: { en: "Warehouse", ps: "سرای" },
  supplier: { en: "Supplier", ps: "عرضه کوونکې کمپنۍ" },
  saraf: { en: "Saraf", ps: "صراف" },
  hawala_no: { en: "Hawala No.", ps: "د حوالې نمبر" },
  cash_in: { en: "Cash In", ps: "نغدې داخله" },
  cash_out: { en: "Cash Out", ps: "نغدې خارجه" },
  drawer: { en: "Cash Drawer", ps: "دخل / نغدې پیسې" },
  currency: { en: "Currency", ps: "اسعار" },
  exchange_rate: { en: "Exchange Rate", ps: "د تبادلې نرخ" },
  cooking_oil: { en: "Cooking Oil", ps: "د پخلي غوړي" },
  sugar: { en: "Sugar", ps: "بوره" },
  bottle: { en: "Bottle", ps: "بوشکه" },
  bag: { en: "Bag", ps: "بوجۍ" },
  order: { en: "Order", ps: "آرډر" },
  waste: { en: "Waste / Loss", ps: "ضایعات" },
  stock: { en: "Stock", ps: "ذخیره" },
  report: { en: "Report", ps: "راپور" },
  print: { en: "Print", ps: "چاپ" },
  save: { en: "Save", ps: "خوندي کول" },
  post: { en: "Post", ps: "ثبتول" },
  new: { en: "New", ps: "نوی" },
  search: { en: "Search", ps: "لټون" },
  status: { en: "Status", ps: "حالت" },
  draft: { en: "Draft", ps: "مسوده" },
  posted: { en: "Posted", ps: "ثبت شوی" },
  received: { en: "Received", ps: "ترلاسه شوی" },
  dispatch: { en: "Dispatch", ps: "لېږد" },
  user: { en: "User", ps: "کارونکی" },
  bank: { en: "Bank", ps: "بانک" },
  note: { en: "Note", ps: "یادښت" },

  // ---------------------------------------------------------------- statuses
  open: { en: "Open", ps: "پرانیستی" },
  closed: { en: "Closed", ps: "تړلی" },
  reversed: { en: "Reversed", ps: "بیرته شوی" },
  partially_received: { en: "Partially Received", ps: "یو څه ترلاسه شوي" },
  resolved: { en: "Resolved", ps: "حل شوی" },
  active: { en: "Active", ps: "فعال" },
  inactive: { en: "Inactive", ps: "غیر فعال" },
  ok: { en: "OK", ps: "سم" },
  warning: { en: "Warning", ps: "خبرداری" },
  critical: { en: "Critical", ps: "جدي ستونزه" },

  // ---------------------------------------------------------------- actions
  edit: { en: "Edit", ps: "سمول" },
  delete: { en: "Delete", ps: "ړنګول" },
  cancel: { en: "Cancel", ps: "لغوه کول" },
  confirm: { en: "Confirm", ps: "تاییدول" },
  close: { en: "Close", ps: "تړل" },
  back: { en: "Back", ps: "شاته" },
  reverse: { en: "Reverse", ps: "بیرته کول" },
  history: { en: "History", ps: "تاریخچه" },
  export_csv: { en: "Export CSV", ps: "CSV ته ایستل" },
  add_line: { en: "Add Line", ps: "کرښه ورزیاتول" },
  remove: { en: "Remove", ps: "لرې کول" },
  sign_in: { en: "Sign In", ps: "ننوتل" },
  sign_out: { en: "Sign Out", ps: "وتل" },
  refresh: { en: "Refresh", ps: "تازه کول" },
  run_checks: { en: "Run Checks", ps: "کتنې چلول" },
  close_day: { en: "Close Day", ps: "د ورځې تړل" },
  view: { en: "View", ps: "کتل" },
  actions: { en: "Actions", ps: "کړنې" },
  create: { en: "Create", ps: "جوړول" },
  loading: { en: "Loading…", ps: "بارېږي…" },
  saving: { en: "Saving…", ps: "خوندي کېږي…" },
  posting: { en: "Posting…", ps: "ثبتېږي…" },

  // ---------------------------------------------------------------- fields
  name: { en: "Name", ps: "نوم" },
  name_ps: { en: "Name (Pashto)", ps: "نوم (پښتو)" },
  full_name: { en: "Full Name", ps: "بشپړ نوم" },
  email: { en: "Email", ps: "برېښنالیک" },
  password: { en: "Password", ps: "پټ نوم" },
  role: { en: "Role", ps: "دنده" },
  phone: { en: "Phone", ps: "تلیفون" },
  address: { en: "Address", ps: "پته" },
  contact: { en: "Contact Person", ps: "د اړیکې کس" },
  country: { en: "Country", ps: "هېواد" },
  keeper_name: { en: "Warehouse Keeper", ps: "د سرای مسوول" },
  product: { en: "Product", ps: "توکی" },
  variant: { en: "Product / Size", ps: "توکی / اندازه" },
  size: { en: "Size", ps: "اندازه" },
  unit: { en: "Unit", ps: "واحد" },
  kg: { en: "KG", ps: "کیلو" },
  kg_per_bag: { en: "KG per Bag", ps: "کیلو په بوجۍ کې" },
  doc_no: { en: "Doc No.", ps: "د سند نمبر" },
  entry_no: { en: "Entry No.", ps: "د ثبت نمبر" },
  supplier_invoice_no: { en: "Supplier Invoice No.", ps: "د کمپنۍ د بل نمبر" },
  bank_name: { en: "Bank Name", ps: "د بانک نوم" },
  bank_balance_due: { en: "Bank Balance Due", ps: "د بانک پاتې مبلغ" },
  total_amount: { en: "Total Amount", ps: "ټول مبلغ" },
  bottles_per_container: { en: "Units per Container", ps: "په کانټینر کې دانې" },
  containers_count: { en: "No. of Containers", ps: "د کانټینرونو شمېر" },
  price_per_unit: { en: "Price per Unit", ps: "د یوې دانې بیه" },
  line_total: { en: "Line Total", ps: "د کرښې ټوله" },
  trucks_total: { en: "Trucks (Total)", ps: "ټولې لارۍ" },
  trucks_received: { en: "Trucks Received", ps: "راغلې لارۍ" },
  trucks_remaining: { en: "Trucks Remaining", ps: "پاتې لارۍ" },
  bill_number: { en: "Bill Number", ps: "د بل نمبر" },
  bill_refs: { en: "Bill References", ps: "د بلونو نمبرونه" },
  qty_expected: { en: "Qty Expected", ps: "تمه شوی مقدار" },
  qty_received: { en: "Qty Received", ps: "ترلاسه شوی مقدار" },
  qty_waste: { en: "Qty Waste", ps: "ضایع شوی مقدار" },
  truck_ref: { en: "Truck Ref.", ps: "د لارۍ نمبر" },
  category: { en: "Category", ps: "ډول" },
  paid_via: { en: "Paid Via", ps: "د تادیې لاره" },
  method: { en: "Method", ps: "طریقه" },
  cash: { en: "Cash", ps: "نغدې" },
  payable: { en: "On Account (Payable)", ps: "په حساب (پور)" },
  direction: { en: "Direction", ps: "لوری" },
  fx_rate: { en: "FX Rate", ps: "د تبادلې نرخ" },
  fx_note: { en: "FX Note", ps: "د تبادلې یادښت" },
  opening_balance: { en: "Opening Balance", ps: "پرانیستی بیلانس" },
  closing_balance: { en: "Closing Balance", ps: "وروستی بیلانس" },
  running_balance: { en: "Running Balance", ps: "روان بیلانس" },
  counted: { en: "Counted (Physical)", ps: "شمېرل شوې (فزیکي)" },
  computed: { en: "Computed (System)", ps: "حساب شوې (سیسټم)" },
  variance: { en: "Variance", ps: "توپیر" },
  variance_explanation: { en: "Variance Explanation", ps: "د توپیر تشریح" },
  debit: { en: "Debit", ps: "ډیبټ (پور ورکول)" },
  credit: { en: "Credit", ps: "کریډټ (پور اخیستل)" },
  account: { en: "Account", ps: "حساب" },
  account_code: { en: "Account Code", ps: "د حساب کوډ" },
  from_date: { en: "From Date", ps: "له نېټې" },
  to_date: { en: "To Date", ps: "تر نېټې" },
  notes: { en: "Notes", ps: "یادښتونه" },
  created_by: { en: "Created by", ps: "جوړوونکی" },
  posted_by: { en: "Posted by", ps: "ثبتوونکی" },
  created_at: { en: "Created at", ps: "د جوړېدو نېټه" },
  is_active: { en: "Active", ps: "فعال" },
  advance: { en: "Advance", ps: "پیشکي" },
  settlement: { en: "Bank Settlement", ps: "د بانک تادیه" },
  kind: { en: "Kind", ps: "ډول" },
  reason: { en: "Reason", ps: "دلیل" },
  auto_cost: { en: "Auto Cost / Unit", ps: "اتومات قیمت / دانه" },
  final_cost: { en: "Final Cost / Unit", ps: "وروستی قیمت / دانه" },
  lock: { en: "Lock", ps: "قلفول" },
  locked: { en: "Locked", ps: "قلف شوی" },
  old_value: { en: "Old Value", ps: "پخوانی ارزښت" },
  new_value: { en: "New Value", ps: "نوی ارزښت" },
  action: { en: "Action", ps: "کړنه" },
  table: { en: "Table", ps: "جدول" },
  record: { en: "Record", ps: "سند" },
  severity: { en: "Severity", ps: "جدیت" },
  check: { en: "Check", ps: "کتنه" },
  last_run: { en: "Last Run", ps: "وروستۍ کتنه" },
  details: { en: "Details", ps: "جزئیات" },
  period: { en: "Period", ps: "موده" },
  system_balance: { en: "System Balance", ps: "د سیسټم بیلانس" },
  external_balance: { en: "Stated Balance", ps: "ویل شوی بیلانس" },
  aging: { en: "Receivable Aging", ps: "د پورونو عمر" },
  days_0_7: { en: "0–7 days", ps: "۰–۷ ورځې" },
  days_8_30: { en: "8–30 days", ps: "۸–۳۰ ورځې" },
  days_31_plus: { en: "31+ days", ps: "۳۱+ ورځې" },
  last_payment: { en: "Last Payment", ps: "وروستۍ تادیه" },
  overview: { en: "Overview", ps: "عمومي حال" },
  payments: { en: "Payments", ps: "تادیات" },
  dispatches: { en: "Dispatches", ps: "لېږدونه" },
  in_transit: { en: "In Transit", ps: "په لار کې" },
  central_stock: { en: "Central / Transit Stock", ps: "مرکزي / انتقالي ذخیره" },
  goods_received_confirm: { en: "Confirm Goods Received", ps: "د توکو رسېدل تایید کړئ" },
  buyer_name: { en: "Buyer Name", ps: "د پیرودونکي نوم" },
  pickup: { en: "Pickup", ps: "وړل" },
  adjustment: { en: "Adjustment", ps: "سمون" },
  movement_type: { en: "Movement Type", ps: "د حرکت ډول" },
  rows: { en: "rows", ps: "کرښې" },
  of: { en: "of", ps: "له" },
  page: { en: "Page", ps: "پاڼه" },
  no_data: { en: "No records found", ps: "هیڅ سند ونه موندل شو" },
  all: { en: "All", ps: "ټول" },
  totals: { en: "Totals", ps: "ټولې" },
  signature: { en: "Signature", ps: "لاسلیک" },
  prepared_by: { en: "Prepared by", ps: "چمتو کوونکی" },
  approved_by: { en: "Approved by", ps: "تایید کوونکی" },
  admin: { en: "Admin", ps: "اډمین" },
  office: { en: "Office", ps: "دفتر" },
  warehouse_role: { en: "Warehouse Keeper", ps: "د سرای مسوول" },

  // ---------------------------------------------------------------- messages
  posting_permanent: {
    en: "Posting is permanent. Corrections require a reversal.",
    ps: "ثبت دایمي دی. سمون یوازې د بیرته کولو له لارې کېږي.",
  },
  confirm_post_title: { en: "Post this document?", ps: "دا سند ثبت کړئ؟" },
  confirm_reverse_title: { en: "Reverse this document?", ps: "دا سند بیرته کړئ؟" },
  reverse_reason_prompt: { en: "Reason for reversal (required)", ps: "د بیرته کولو دلیل (اړین)" },
  day_close_warning: {
    en: "Closing the day locks all cash entries for this date.",
    ps: "د ورځې تړل د دې نېټې ټولې نغدې راکړې ورکړې قلفوي.",
  },
  variance_must_be_explained: {
    en: "The day cannot close with an unexplained variance.",
    ps: "ورځ د ناتشریح شوي توپیر سره نه تړل کېږي.",
  },
  login_failed: { en: "Sign-in failed. Check email and password.", ps: "ننوتل ونشول. برېښنالیک او پټ نوم وګورئ." },
  no_profile: {
    en: "Your account has no profile yet. Contact the administrator.",
    ps: "ستاسو حساب تر اوسه پروفایل نلري. له اډمین سره اړیکه ونیسئ.",
  },
  bootstrap_admin_title: { en: "First-time setup: create the administrator", ps: "لومړنی تنظیم: اډمین جوړ کړئ" },
  session_expired: { en: "Session expired. Sign in again.", ps: "ناسته پای ته ورسېده. بیا ننوځئ." },
  are_you_sure: { en: "Are you sure?", ps: "ډاډه یاست؟" },
  required_field: { en: "This field is required", ps: "دا برخه اړینه ده" },
  invalid_number: { en: "Invalid number", ps: "ناسم شمېر" },
  must_be_positive: { en: "Must be greater than zero", ps: "باید له صفر زیات وي" },
  stock_insufficient: { en: "Insufficient stock", ps: "ذخیره کافي نه ده" },
  saved_ok: { en: "Saved", ps: "خوندي شو" },
  posted_ok: { en: "Posted", ps: "ثبت شو" },
  error_occurred: { en: "An error occurred", ps: "ستونزه رامنځته شوه" },
  estimate_note: {
    en: "Estimate — currency conversions use the manual rates recorded on each transaction.",
    ps: "اټکل — د اسعارو بدلون د هرې راکړې ورکړې د لاسي نرخ له مخې دی.",
  },
  waste_absorbed_note: {
    en: "Waste is absorbed by the company and inflates landed cost per unit.",
    ps: "ضایعات کمپنۍ په غاړه اخلي او د یوې دانې تمام شده قیمت لوړوي.",
  },
  saraf_not_in_roznamcha: {
    en: "Saraf transactions do not appear in the Roznamcha — only physical drawer cash.",
    ps: "د صراف راکړې ورکړې په روزنامچه کې نه راځي — یوازې د دخل نغدې پیسې.",
  },

  // ---------------------------------------------------------------- reports
  report_supplier_statement: { en: "Supplier Statement", ps: "د عرضه کوونکي حساب" },
  report_warehouse_statement: { en: "Warehouse Statement (Money)", ps: "د سرای حساب (پیسې)" },
  report_warehouse_stock: { en: "Warehouse Stock Report", ps: "د سرای د ذخیرې راپور" },
  report_order_status: { en: "Order Status Report", ps: "د آرډر د حالت راپور" },
  report_landed_cost: { en: "Landed Cost Report", ps: "د تمام شده قیمت راپور" },
  report_saraf_statement: { en: "Saraf Statement", ps: "د صراف حساب" },
  report_roznamcha_daily: { en: "Roznamcha Daily Sheet", ps: "د روزنامچې ورځنۍ پاڼه" },
  report_monthly_cash: { en: "Monthly Cash Summary", ps: "د میاشتنۍ نغدو لنډیز" },
  report_sales_summary: { en: "Sales / Dispatch Summary", ps: "د پلور / لېږد لنډیز" },
  report_expense_by_category: { en: "Expenses by Category", ps: "لګښتونه د ډول له مخې" },
  report_receivables_aging: { en: "Receivables Aging", ps: "د پورونو عمر" },
  report_order_profit: { en: "Profit Estimate per Order", ps: "د آرډر د ګټې اټکل" },
} as const satisfies Record<string, Label>;

export type LabelKey = keyof typeof labels;

/** Plain-string form: "English / پښتو" — for placeholders, titles, print. */
export function lbl(k: LabelKey): string {
  const l = labels[k];
  return `${l.en} / ${l.ps}`;
}

export function lblEn(k: LabelKey): string {
  return labels[k].en;
}

export function lblPs(k: LabelKey): string {
  return labels[k].ps;
}
